bboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('all/', BbListView.as_view(), name='bbs_list')
]

contest/urls.py
from django.urls import path

from .views import IndexTemplateView

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),

]

contest_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


class RedView(RedirectView):
    url = 'bboard'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bboard/', include('bboard.urls'), name='bboard'),
    path('', RedView.as_view())
]

bboard/models.py
from django.db import models


# Create your models here.
class Bb(models.Model):
    title = models.CharField(
        max_length=150,
        verbose_name='Название'
    )
    body = models.TextField(
        max_length=500,
        verbose_name='Описание объявления',
        blank=True,
        null=True
    )
    price = models.FloatField(
        verbose_name='Цена',
        blank=True,
        null=True
    )
    rubric = models.ForeignKey(
        'Rubric',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Rubric(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='Название'
    )

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'

contest/models.py
from django.db import models

# Create your models here.

bboard/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from .models import Bb, Rubric

# Create your views here.
def index(request):
    return render(request, 'bboard/index.html')

class BbListView(ListView):
    model = Bb
    template_name = 'bboard/bb/list.html'

contest/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexTemplateView(TemplateView):
    template_name = 'contest/index.html'

templates/bboard/bb/list.html
{% extends 'layout/based.html' %}

{% block title %}
    Все объявления -  {{ block.super }}
{% endblock %}

{% block content %}
    <p class="display-3">
        Список объявлений
    </p>
    <div class="row">
        {% for bb in bb_list %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ bb.title }}</h5>
                        <p class="card-text">С вспомогательным текстом ниже в качестве естественного перехода к
                            дополнительному контенту.</p>
                        <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/bboard/index.html
{% extends 'layout/based.html' %}
{% block title %}
    Приветствие - {{ block.super }}
{% endblock %}

{% block content %}
    Привет
{% endblock %}

templates/contest/index.html
{% extends 'layout/based.html' %}

templates/layout/based.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="CnPcBWBKKYcTjTb9iBI1yRQikaAQoa3nqt80w4xC3ho"/>

    <title>
        {% block title %}
            ДОСКА ОБЪЯВЛЕНИЙ
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
            integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
</head>
<body>

<div class="col">
    {% include 'layout/includes/navbar_include.html' %}
</div>
<main class="container pt-3 pb-3">
    {% block content %}

    {% endblock %}
</main>

{% include 'layout/includes/footer_include.html' %}

</body>
</html>

templates/layout/includes/footer_include.html
<footer class="bg-dark text-center text-white fixed-bottom mt-5">
    <!-- Grid container -->
    <div class="container p-2 pb-0">
        <!-- Section: Social media -->
        <section class="mb-2">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="bi bi-facebook"></i>
            </a>

            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="bi bi-twitter"></i>
            </a>

            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="bi bi-google"></i
            ></a>
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="bi bi-instagram"></i
            ></a>

            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="bi bi-linkedin   "></i
            ></a>

            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
            ><i class="bi-github"></i
            ></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
</footer>

templates/layout/includes/navbar_include.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar scroll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'bbs_list' %}">Список объявений</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Link
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Link</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>